config/routes.rb
Rails.application.routes.draw do
  root 'matches#index'

  get 'matches', to: 'matches#index'
  # get 'matches/:id', to: 'matches#show'

  get '/about', to: redirect('/wtf'), as: 'about_redirect'
  get '/wtf', to: 'pages#about', as: 'about'

  namespace :admin do
    resources :matches, only: [:new, :create, :edit, :update] do
      resources :goals, only: [:new, :create, :edit, :update]
    end
  end
end

app/models/appearance.rb
# Player's match appearance
class Appearance
  include Mongoid::Document

  # fake
  field :_id

  field :name, type: String

  field :min_in, type: Integer
  field :min_in_extra, type: Integer
  field :min_out, type: Integer
  field :min_out_extra, type: Integer

  belongs_to :person
  embeds_one :team_ref
end

app/models/card.rb
class Card < Event
  field :type, type: String
  validates :type, inclusion: { in: %w(yellow red) }
end

app/models/coach_appearance.rb
# Coach's match appearance
class CoachAppearance
  include Mongoid::Document

  # fake
  field :_id

  field :name, type: String

  belongs_to :person
  embeds_one :team_ref
end

app/models/concerns/textified_array.rb
module TextifiedArray
  extend ActiveSupport::Concern

  SCORE_TEXT_FORMAT = /^\d{1,2}-\d{1,2}$/

  module ClassMethods
    def textified_array(name, opts)
      separator = opts[:separator] || ", "

      define_method("#{name}_text=") do |text|
        self.send("#{name}=", text.split(separator).collect(&:strip)) unless text.blank?
      end

      define_method("#{name}_text") do
        values = self.send(name)
        return "" if values.blank?
        values.join(separator)
      end
    end
  end
end

app/models/event.rb
# Match event (goal, booking, etc)
class Event
  include Mongoid::Document

  embedded_in :match

  # field :_id, type: String

  # Person name
  field :name, type: String

  field :min, type: Integer
  field :min_extra, type: Integer

  # belongs_to :person
  embeds_one :team, class_name: "MatchTeam"
end

app/models/goal.rb
class Goal < Event
  include TextifiedArray

  field :score, type: Array
  textified_array :score, separator: "-"
  # validates :score, length: { is: 2, allow_blank: true }

  field :type, type: String
  VALID_TYPES = %w(goal own penalty)
  validates :type, inclusion: { in: VALID_TYPES }
end

app/models/match.rb
class Match
  include Mongoid::Document

  field :_id, type: String

  # Kick-off date (UTC)
  # (it's a string as date might be incomplete)
  field :date, type: String

  # Kick-off time (UTC)
  field :time, type: String

  # Home and away team
  embeds_many :teams, class_name: "MatchTeam"

  # Scorecard
  embeds_one :scorecard

  # Competition
  embeds_one :competition, class_name: "MatchCompetition"

  # Goals
  embeds_many :goals

  # Line-up
  embeds_many :appearances
  alias_method :players, :appearances

  # Coaches
  embeds_many :coach_appearances
  alias_method :coaches, :coach_appearances
  validates :coach_appearances, length: { is: 2, allow_blank: true }

  # Venue
  embeds_one :venue

  # Neutral ground
  field :neutral, type: Boolean

  # Special match status
  field :status, type: String
  validates :status, inclusion: { in: %w(suspended postponed), allow_blank: true }

  include Mongoid::Timestamps

  set_callback(:create, :before) do |match|
    match._id = "#{match.date} #{match.teams[0].name} #{match.teams[1].name}".parameterize
  end

  def score
    scorecard && scorecard.score_text
  end

  def competition_name
    competition && competition.name
  end
end

app/models/match_competition.rb
class MatchCompetition
  include Mongoid::Document

  embedded_in :match

  # fake
  field :_id

  field :name, type: String
end

app/models/match_team.rb
class MatchTeam
  include Mongoid::Document

  embedded_in :match

  # fake
  field :_id

  field :name, type: String

  # belongs_to :team
end

app/models/person.rb
# Person (player and/or coach)
class Person
  include Mongoid::Document

  field :_id, type: String

  field :name, type: String

  field :first_name, type: String
  field :last_name, type: String
end

app/models/scorecard.rb
class Scorecard
  include Mongoid::Document
  include TextifiedArray

  embedded_in :match

  # fake
  field :_id

  # Final score (after 2nd half or after extra time)
  field :score, type: Array
  textified_array :score, separator: "-"

  # Half-time (1st half) score
  field :ht, type: Array
  textified_array :ht, separator: "-"

  # After 2nd half score
  field :ft, type: Array
  textified_array :ft, separator: "-"

  # After extra time score
  field :aet, type: Array
  textified_array :aet, separator: "-"

  # Penalty shootout score
  field :pso, type: Array
  textified_array :pso, separator: "-"

  # TODO: walkover (wo) -> Array or Bool? or at Match level?
end

app/models/venue.rb
class Venue
  include Mongoid::Document

  embedded_in :match

  # fake
  field :_id

  field :name, type: String
  field :city, type: String
end

app/controllers/admin/goals_controller.rb
class Admin::GoalsController < ApplicationController
  def new
    @match = Match.find(params[:match_id])
    @goal = Goal.new
    @form = GoalForm.new(@goal)
    @form.prepopulate!
  end

  def create
    @match = Match.find(params[:match_id])
    @goal = Goal.new
    @form = GoalForm.new(@goal)

    if @form.validate(params[:goal])
      @form.sync
      @match.goals << @goal
      @match.save

      redirect_to matches_path, notice: "Goal added"
    else
      flash.now[:error] = "Could not save match. Fix errors."
      render "new"
    end
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
  def new
    @match = Match.new
    @form = MatchForm.new(@match)
    @form.prepopulate!
  end

  def create
    @match = Match.new
    @form = MatchForm.new(@match)

    if @form.validate(params[:match])
      @form.sync
      @match.save

      redirect_to matches_path, notice: "Match added (#{@match.date}: #{@match.teams[0].name} - #{@match.teams[1].name})"
    else
      flash.now[:error] = "Could not save match. Fix errors."
      render "new"
    end
  end

  def edit
    @match = Match.find(params[:id])
    @form = MatchForm.new(@match)
  end

  def update
    @match = Match.find(params[:id])
    @form = MatchForm.new(@match)

    if @form.validate(params[:match])
      @form.sync
      @match.save

      redirect_to matches_path, notice: "Match saved (#{@match.date}: #{@match.teams[0].name} - #{@match.teams[1].name})"
    else
      flash.now[:error] = "Could not save match. Fix errors."
      render "edit"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.order_by({date: "DESC", time: "DESC"})
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def admin(&block)
    content_tag :div, class: 'admin' do
      block.call
    end
  end

  def submit_button(form, text)
    content = form.button(:button, text)
    content += link_to("Cancel", :back)
    content_tag(:div, content, class: "pure-controls")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/goals/_form.html.erb
<%= simple_form_for form, :url => url do |f| %>

  <fieldset>
    <%= f.input :type, collection: Goal::VALID_TYPES, as: :radio_buttons, label_html: { class: "pure-radio" } %>
    <%= f.simple_fields_for :team, @form.team do |tf| -%>
      <%= tf.input :name, label: "Team", collection: @match.teams.collect(&:name), as: :radio_buttons, label_html: { class: "pure-radio" } %>
    <% end %>
    <%= f.input :name, label: "Player name" %>
    <%= f.input :min, input_html: { class: "pure-input-1-10" } %>
    <%= f.input :min_extra, input_html: { class: "pure-input-1-10" } %>
    <%= f.input :score_text, label: "Score", hint: "eg. 2-1", input_html: { class: "pure-input-1-10" } %>
  </fieldset>

  <%= submit_button(f, (defined?(submit_text) ? submit_text : "Save")) %>
<% end %>

app/views/admin/goals/new.html.erb
<section>
  <h1>New goal (<%= @match._id %>)</h1>

  <%= render "admin/goals/form", form: @form, url: admin_match_goals_path, submit_text: "Add goal" %>
</section>

app/views/admin/matches/_form.html.erb
<%= simple_form_for form, :url => url do |f| %>

  <fieldset>
    <legend>Date &amp; time</legend>

    <%= f.input :date, hint: "Any readbale format (preferred: yyyy-mm-dd)", input_html: { class: "pure-input-1-6" } %>
    <%= f.input :time, hint: "Format: mm:ss, eg. 20:00", input_html: { class: "pure-input-1-10" } %>

  </fieldset>
  <fieldset>
    <legend>Competition</legend>

    <%= f.simple_fields_for :competition do |cf| -%>
      <%= cf.input :name, label: "Competition", input_html: { class: "pure-input-1-3" }  %>
    <% end -%>

  </fieldset>
  <fieldset>
    <legend>Teams</legend>

    <%= f.simple_fields_for :teams, @form.teams[0] do |tf| -%>
      <%= tf.input :name, label: "Home team" %>
    <% end %>

    <%= f.simple_fields_for :teams, @form.teams[1] do |tf| -%>
      <%= tf.input :name, label: "Away team" %>
    <% end -%>
  </fieldset>

  <fieldset>
    <legend>Score</legend>

    <%= f.simple_fields_for :scorecard do |sf| -%>
      <%= sf.input :score_text, label: "Score", hint: "eg. 4-2", input_html: { class: "pure-input-1-10" } %>
      <%= sf.input :pso_text, label: "Penalty shootout", input_html: { class: "pure-input-1-10" } %>
    <% end -%>
  </fieldset>

  <fieldset>
    <legend>Venue</legend>

    <%= f.simple_fields_for :venue do |vf| -%>
      <%= vf.input :name, label: "Venue name" %>
      <%= vf.input :city, label: "Venue city" %>
    <% end -%>
  </fieldset>

  <%= submit_button(f, (defined?(submit_text) ? submit_text : "Save")) %>

<% end %>

app/views/admin/matches/edit.html.erb
<section>
  <h1>Edit match (<%= @form.model._id %>)</h1>

  <%= render "admin/matches/form", form: @form, url: admin_match_path(@form.model._id) %>
</section>

app/views/admin/matches/new.html.erb
<section>
  <h1>New match</h1>

  <%= render "admin/matches/form", form: @form, url: admin_matches_path, submit_text: "Add match" %>
</section>

app/views/matches/index.html.erb
<section>
  <h1>Matches</h1>

  <%= admin do %>
    <p><a href="<%= new_admin_match_path %>">add match</a></p>
  <% end %>

  <table class="matches-list">
    <% @matches.each do |m| %>
      <tr>
        <td><%= "#{m.date} #{m.time}" %></td>
        <td><%= "#{m.competition_name}" %></td>
        <td><%= "#{m.teams[0]['name']}" %></td>
        <td><%= "#{m.teams[1]['name']}" %></td>
        <td><%= "#{m.score}" %></td>
        <td><%= admin do %><a href="<%= edit_admin_match_path(m._id) %>">edit</a><% end %></td>
        <td><%= admin do %><a href="<%= new_admin_match_goal_path(m._id) %>">add goal</a><% end %></td>
      </tr>
      <% if m.goals %>
        <% m.goals.sort_by { |g| [g.score[0], g.score[1]] }.each do |g| %>
        <tr>
          <td colspan="2">&nbsp;</td>
          <% if m.teams[0]['name'] != g.team.name %><td>&nbsp;</td><% end %>
          <td>
            <%= "#{g.min}" %>'<%= "+#{g.min_extra}" if g.min_extra %>
            <%= "#{g.name}" %>
            (<%= "#{g.type}" %>)
          </td>
          <% if m.teams[0]['name'] == g.team.name %><td>&nbsp;</td><% end %>
          <td><%= "#{g.score_text}" %></td>
          <td colspan="2"><%= admin do %>edit (TODO)<% end %></td>
        </tr>
        <% end %>
      <% end %>
    <% end %>
  </table>
</section>